In [40]:
import exponential_new
import numpy as np
import pandas as pd
from cutoffs_new import Polynomial
#import tensorflow as tf
import matplotlib.pyplot as plt
#import keras
#from tensorflow.keras import layers
#from tensorflow.keras.layers.experimental import preprocessing
from scipy.optimize import minimize
turbs = ["Siemens"] *2
turbs_3 = ["Siemens"] *3
nl=exponential_new.NeighborlistCalculator(cutoff=4001,cone_grad=0.12582561117875557, cone_offset=72.24947126849844)
Gs = {"Siemens": [{"type":"G2", "turbine":"Siemens","eta":1, "offset": 1.},
                  {"type":"G4", "elements":"Siemens","eta":1, "gamma":4., "zeta": 1.0},
#                  {"type":"G6", "elements":"Siemens","eta":1, "gamma": 0.5, "zeta": 1.0}
                 ]}
finpr=exponential_new.FingerprintCalculator(cutoff=4001,Gs=Gs,Rct=3000,delta_R=100,cone_grad=0.12582561117875557, cone_offset=72.24947126849844)

symbol="Siemens"
dataset_pos=np.empty(shape=(0, 2))
dataset_fp=np.empty(shape=(0, 2))
dataset_pri=np.empty(shape=(0, 1))
dataset_ws=np.empty(shape=(0, 1))


In [2]:
def build_and_compile_model(norm):
    model = keras.Sequential([
        norm,
        layers.Dense(64, activation='relu'),
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dense(1)
    ])
    model.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))
    return model

In [3]:
dataset = pd.read_csv('all_dataset.csv', index_col=0)
len(dataset)

1784

In [13]:
for i,row in dataset.iterrows():
    if row['Num_tot_turb'] == 3:
        position = np.array([[dataset.at[i,"X_coord"],dataset.at[i,"Y_coord"]],[dataset.at[i,"X_coord"],id_dataset.at[1,"Y_coord"]],[id_dataset.at[2,"X_coord"],id_dataset.at[2,"Y_coord"]]])

NameError: name 'id_dataset' is not defined

In [17]:
k=0
count=0
dataset["IDnum"]=pd.Series()
for i in range(len(dataset)):
    dataset.at[i,"IDnum"]=k
    print(i,k,dataset["Num_tot_turb"].iloc[i])
    count = count +1
    if (count==dataset["Num_tot_turb"].iloc[i]):
        k=k+1
        count=0
dataset

0 0 2.0
1 0 2.0
2 1 2.0
3 1 2.0
4 2 2.0
5 2 2.0
6 3 2.0
7 3 2.0
8 4 2.0
9 4 2.0
10 5 2.0
11 5 2.0
12 6 2.0
13 6 2.0
14 7 2.0
15 7 2.0
16 8 2.0
17 8 2.0
18 9 2.0
19 9 2.0
20 10 2.0
21 10 2.0
22 11 2.0
23 11 2.0
24 12 2.0
25 12 2.0
26 13 2.0
27 13 2.0
28 14 2.0
29 14 2.0
30 15 2.0
31 15 2.0
32 16 2.0
33 16 2.0
34 17 2.0
35 17 2.0
36 18 2.0
37 18 2.0
38 19 2.0
39 19 2.0
40 20 2.0
41 20 2.0
42 21 2.0
43 21 2.0
44 22 2.0
45 22 2.0
46 23 2.0
47 23 2.0
48 24 2.0
49 24 2.0
50 25 2.0
51 25 2.0
52 26 2.0
53 26 2.0
54 27 2.0
55 27 2.0
56 28 2.0
57 28 2.0
58 29 2.0
59 29 2.0
60 30 2.0
61 30 2.0
62 31 2.0
63 31 2.0
64 32 2.0
65 32 2.0
66 33 2.0
67 33 2.0
68 34 2.0
69 34 2.0
70 35 2.0
71 35 2.0
72 36 2.0
73 36 2.0
74 37 2.0
75 37 2.0
76 38 2.0
77 38 2.0
78 39 2.0
79 39 2.0
80 40 2.0
81 40 2.0
82 41 2.0
83 41 2.0
84 42 2.0
85 42 2.0
86 43 2.0
87 43 2.0
88 44 2.0
89 44 2.0
90 45 2.0
91 45 2.0
92 46 2.0
93 46 2.0
94 47 2.0
95 47 2.0
96 48 2.0
97 48 2.0
98 49 2.0
99 49 2.0
100 50 2.0
101 50 2.0
102 51 2

/var/folders/mq/w3kgld3j4d7_9jz6mhxw6fg40000gs/T/ipykernel_15423/1936061737.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset["IDnum"]=pd.Series()


X_coord     Y_coord  Ref_wind  Num_tot_turb  \
0        0.000000    0.000000  7.479762           2.0   
1      241.621088  139.500000  7.576231           2.0   
2        0.000000    0.000000  7.473602           2.0   
3      244.018898  135.261884  7.567527           2.0   
4        0.000000    0.000000  7.467848           2.0   
...           ...         ...       ...           ...   
1779  3164.356744 -110.000000  6.978195           3.0   
1780   499.388946  -80.000000  6.763982           3.0   
1781     0.000000    0.000000  7.306684           3.0   
1782  2630.260284  143.000000  7.232828           3.0   
1783   497.023796 -128.000000  7.301574           3.0   

                                      ID  Turb_num  IDnum  
0     2_turbine_240_degrees_279.0_meters       0.0    0.0  
1     2_turbine_240_degrees_279.0_meters       1.0    0.0  
2     2_turbine_241_degrees_279.0_meters       0.0    1.0  
3     2_turbine_241_degrees_279.0_meters       1.0    1.0  
4     2_turbine_242_degrees_279.0_meters       0.0    2.0  
...                                  ...       ...    ...  
1779          3_turbine_358th_simulation       1.0  710.0  
1780          3_turbine_358th_simulation       2.0  710.0  
1781          3_turbine_359th_simulation       0.0  711.0  
1782          3_turbine_359th_simulation       1.0  711.0  
1783          3_turbine_359th_simulation       2.0  711.0  

[1784 rows x 7 columns]

In [18]:
dataset["Num_tot_turb"]=dataset["Num_tot_turb"].astype(int)
dataset["Turb_num"]=dataset["Turb_num"].astype(int)
dataset["IDnum"]=dataset["IDnum"].astype(int)

In [29]:
numsims=dataset["IDnum"].iloc[-1]+1
print(numsims)
turb = [symbol]

712


In [41]:
count=0
for i in range(numsims):
#    if dataset.loc[dataset['Number of Turbine in the Simulation'] == 2].reset_index(drop=True)
    numturb=dataset["Num_tot_turb"].iloc[count]
    position = np.empty((numturb,2))
    ws = np.empty((numturb,1))
    fp = np.empty((numturb,2))
    for k in range(numturb):
        position[k,0]=dataset.at[count,"X_coord"]
        position[k,1]=dataset.at[count,"Y_coord"]
        ws[k,0]=dataset.at[count,"Ref_wind"]
        count =+ 1
    neigh=nl.calculate(turb*numturb,position)
    fp=finpr.calculate(turb*numturb,position,neigh,symbol)
    fp=np.array(fp)
#    print(fp)
    dataset_pos=np.append(dataset_pos,position,axis=0)
    dataset_fp=np.append(dataset_fp,fp,axis=0)
    dataset_ws=np.append(dataset_ws,ws,axis=0)
dataset_full=np.concatenate((dataset_fp, dataset_ws),axis=1)

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1

In [ ]:
def fitness(x):
    Gs = {"Siemens": [{"type":"G2", "turbine":"Siemens","eta":x[0], "offset": 1.},
                  {"type":"G4", "elements":"Siemens","eta":x[1], "gamma":4., "zeta": 1.0},
                  {"type":"G6", "elements":"Siemens","eta":x[2], "gamma": 0.5, "zeta": 1.0}
                 ]}
    turbs_3 = ["Siemens"] *3
    nl=exponential_new.NeighborlistCalculator(cutoff=4001,cone_grad=0.12582561117875557, cone_offset=72.24947126849844)


    symbol="Siemens"

    
    dataset = pd.DataFrame(dataset, columns = ['Fingerprint(G2)','Fingerprint(G4)','Fingerprint(G6)','Ref_Wind_Speed'])
    train_dataset = dataset.sample(frac=0.8, random_state=0)
    test_dataset = dataset.drop(train_dataset.index)
    train_features = train_dataset.copy()
    test_features = test_dataset.copy()
    all_features = dataset.copy()
    train_labels = train_features.pop('Ref_Wind_Speed')
    test_labels = test_features.pop('Ref_Wind_Speed')
    all_labels = all_features.pop('Ref_Wind_Speed')
    normalizer = preprocessing.Normalization(axis=-1)
    normalizer.adapt(np.array(train_features))
    dnn_model = build_and_compile_model(normalizer)
    history = dnn_model.fit(
        train_features, train_labels,
        validation_split=0.2,
        verbose=0, epochs=120)
    all_predictions = dnn_model.predict(all_features).flatten()
    error_all=np.abs(all_predictions-all_labels)
    return np.max(error_all)

In [ ]:
x0 = [5.3, 5., 2.]
bounds= ((0,10),(0,10),(0,10))
res = minimize(fitness, x0, bounds= bounds, options={'disp':True})